// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AppleAuthRequest
 *
 * Request body for Apple Sign In.
 */
export type AppleAuthRequest = {
    /**
     * Identity Token
     */
    identity_token: string;
    full_name?: FullName | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * AppleAuthResponse
 *
 * Response for Apple Sign In, extends TokenResponse with is_new_user flag.
 */
export type AppleAuthResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Refresh Token
     */
    refresh_token: string;
    /**
     * Token Type
     */
    token_type?: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Username
     */
    username: string;
    /**
     * Is New User
     */
    is_new_user: boolean;
};

/**
 * CarResponse
 */
export type CarResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Year
     */
    year: number;
    /**
     * Make
     */
    make: string;
    /**
     * Model
     */
    model: string;
    /**
     * Trim
     */
    trim?: string | null;
    /**
     * Color
     */
    color: string;
    /**
     * Display Name
     */
    display_name?: string | null;
    /**
     * Photo Url
     */
    photo_url?: string | null;
    /**
     * Mods
     */
    mods?: Array<string> | null;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * CarSummary
 */
export type CarSummary = {
    /**
     * Id
     */
    id: string;
    /**
     * Year
     */
    year: number;
    /**
     * Make
     */
    make: string;
    /**
     * Model
     */
    model: string;
    /**
     * Trim
     */
    trim?: string | null;
    /**
     * Color
     */
    color: string;
    /**
     * Is Active
     */
    is_active: boolean;
};

/**
 * ConvoyMemberOut
 */
export type ConvoyMemberOut = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Username
     */
    username: string;
    /**
     * Display Name
     */
    display_name?: string | null;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
    role: ConvoyMemberRole;
    /**
     * Car Year
     */
    car_year?: number | null;
    /**
     * Car Make
     */
    car_make?: string | null;
    /**
     * Car Model
     */
    car_model?: string | null;
    /**
     * Car Color
     */
    car_color?: string | null;
    /**
     * Joined At
     */
    joined_at: string;
};

/**
 * ConvoyMemberRole
 */
export const ConvoyMemberRole = { LEADER: 'leader', MEMBER: 'member' } as const;

/**
 * ConvoyMemberRole
 */
export type ConvoyMemberRole = typeof ConvoyMemberRole[keyof typeof ConvoyMemberRole];

/**
 * ConvoyMessageOut
 */
export type ConvoyMessageOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Sender Id
     */
    sender_id?: string | null;
    /**
     * Sender Username
     */
    sender_username?: string | null;
    /**
     * Content
     */
    content: string;
    message_type: MessageType;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ConvoyResponse
 */
export type ConvoyResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Leader Id
     */
    leader_id: string;
    visibility: ConvoyVisibility;
    status: ConvoyStatus;
    /**
     * Destination Name
     */
    destination_name?: string | null;
    /**
     * Member Count
     */
    member_count: number;
    /**
     * Members
     */
    members?: Array<ConvoyMemberOut> | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ConvoyStatus
 */
export const ConvoyStatus = {
    FORMING: 'forming',
    ACTIVE: 'active',
    ENDED: 'ended'
} as const;

/**
 * ConvoyStatus
 */
export type ConvoyStatus = typeof ConvoyStatus[keyof typeof ConvoyStatus];

/**
 * ConvoyVisibility
 */
export const ConvoyVisibility = { PUBLIC: 'public', PRIVATE: 'private' } as const;

/**
 * ConvoyVisibility
 */
export type ConvoyVisibility = typeof ConvoyVisibility[keyof typeof ConvoyVisibility];

/**
 * CreateCarRequest
 */
export type CreateCarRequest = {
    /**
     * Year
     */
    year: number;
    /**
     * Make
     */
    make: string;
    /**
     * Model
     */
    model: string;
    /**
     * Trim
     */
    trim?: string | null;
    /**
     * Color
     */
    color: string;
    /**
     * Display Name
     */
    display_name?: string | null;
    /**
     * Photo Url
     */
    photo_url?: string | null;
    /**
     * Mods
     */
    mods?: Array<string> | null;
};

/**
 * CreateConvoyRequest
 */
export type CreateConvoyRequest = {
    /**
     * Name
     */
    name?: string;
    visibility?: ConvoyVisibility;
    /**
     * Destination Name
     */
    destination_name?: string | null;
    /**
     * Destination Lat
     */
    destination_lat?: number | null;
    /**
     * Destination Lng
     */
    destination_lng?: number | null;
};

/**
 * FriendCarSummary
 */
export type FriendCarSummary = {
    /**
     * Id
     */
    id: string;
    /**
     * Year
     */
    year: number;
    /**
     * Make
     */
    make: string;
    /**
     * Model
     */
    model: string;
    /**
     * Trim
     */
    trim?: string | null;
    /**
     * Color
     */
    color: string;
};

/**
 * FriendProfile
 */
export type FriendProfile = {
    /**
     * Id
     */
    id: string;
    /**
     * Username
     */
    username: string;
    /**
     * Display Name
     */
    display_name?: string | null;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
    active_car?: FriendCarSummary | null;
};

/**
 * FriendRequestAction
 */
export type FriendRequestAction = {
    /**
     * Request Id
     */
    request_id: string;
};

/**
 * FriendRequestCreate
 */
export type FriendRequestCreate = {
    /**
     * User Id
     */
    user_id: string;
};

/**
 * FriendRequestOut
 */
export type FriendRequestOut = {
    /**
     * Request Id
     */
    request_id: string;
    from_user: FriendProfile;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * FullName
 *
 * Name components from Apple Sign In.
 */
export type FullName = {
    /**
     * Given Name
     */
    given_name?: string | null;
    /**
     * Family Name
     */
    family_name?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * InviteRequest
 */
export type InviteRequest = {
    /**
     * User Id
     */
    user_id: string;
};

/**
 * KickRequest
 */
export type KickRequest = {
    /**
     * User Id
     */
    user_id: string;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * MessageResponse
 */
export type MessageResponse = {
    /**
     * Message
     */
    message: string;
};

/**
 * MessageType
 */
export const MessageType = {
    TEXT: 'text',
    SYSTEM: 'system',
    QUICK_ACTION: 'quick_action'
} as const;

/**
 * MessageType
 */
export type MessageType = typeof MessageType[keyof typeof MessageType];

/**
 * PublicUserProfile
 *
 * Profile visible to other users.
 */
export type PublicUserProfile = {
    /**
     * Id
     */
    id: string;
    /**
     * Username
     */
    username: string;
    /**
     * Display Name
     */
    display_name?: string | null;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
    active_car?: CarSummary | null;
};

/**
 * QuickActionRequest
 */
export type QuickActionRequest = {
    /**
     * Action
     */
    action: string;
};

/**
 * RefreshRequest
 */
export type RefreshRequest = {
    /**
     * Refresh Token
     */
    refresh_token: string;
};

/**
 * RegisterRequest
 */
export type RegisterRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Username
     */
    username?: string | null;
    /**
     * Display Name
     */
    display_name?: string | null;
};

/**
 * RouteResponse
 */
export type RouteResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Destination Name
     */
    destination_name: string;
    /**
     * Destination Lat
     */
    destination_lat: number;
    /**
     * Destination Lng
     */
    destination_lng: number;
    /**
     * Set By Username
     */
    set_by_username: string;
    /**
     * Waypoints
     */
    waypoints?: Array<Waypoint> | null;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * SendMessageRequest
 */
export type SendMessageRequest = {
    /**
     * Content
     */
    content: string;
};

/**
 * SetRouteRequest
 */
export type SetRouteRequest = {
    /**
     * Destination Name
     */
    destination_name: string;
    /**
     * Destination Lat
     */
    destination_lat: number;
    /**
     * Destination Lng
     */
    destination_lng: number;
    /**
     * Waypoints
     */
    waypoints?: Array<Waypoint> | null;
};

/**
 * SpeedUnit
 */
export const SpeedUnit = { MPH: 'mph', KPH: 'kph' } as const;

/**
 * SpeedUnit
 */
export type SpeedUnit = typeof SpeedUnit[keyof typeof SpeedUnit];

/**
 * TokenResponse
 */
export type TokenResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Refresh Token
     */
    refresh_token: string;
    /**
     * Token Type
     */
    token_type?: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Username
     */
    username: string;
};

/**
 * UpdateCarRequest
 */
export type UpdateCarRequest = {
    /**
     * Year
     */
    year?: number | null;
    /**
     * Make
     */
    make?: string | null;
    /**
     * Model
     */
    model?: string | null;
    /**
     * Trim
     */
    trim?: string | null;
    /**
     * Color
     */
    color?: string | null;
    /**
     * Display Name
     */
    display_name?: string | null;
    /**
     * Photo Url
     */
    photo_url?: string | null;
    /**
     * Mods
     */
    mods?: Array<string> | null;
};

/**
 * UpdateConvoyRequest
 */
export type UpdateConvoyRequest = {
    /**
     * Name
     */
    name?: string | null;
    visibility?: ConvoyVisibility | null;
};

/**
 * UpdateProfileRequest
 */
export type UpdateProfileRequest = {
    /**
     * Username
     */
    username?: string | null;
    /**
     * Display Name
     */
    display_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Phone Number
     */
    phone_number?: string | null;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
    visibility?: VisibilityMode | null;
    /**
     * Discovery Radius Miles
     */
    discovery_radius_miles?: number | null;
    speed_unit?: SpeedUnit | null;
};

/**
 * UserProfile
 */
export type UserProfile = {
    /**
     * Id
     */
    id: string;
    /**
     * Username
     */
    username: string;
    /**
     * Display Name
     */
    display_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Phone Number
     */
    phone_number?: string | null;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
    visibility: VisibilityMode;
    /**
     * Discovery Radius Miles
     */
    discovery_radius_miles: number;
    speed_unit: SpeedUnit;
    active_car?: CarSummary | null;
};

/**
 * UserSearchResult
 */
export type UserSearchResult = {
    /**
     * Id
     */
    id: string;
    /**
     * Username
     */
    username: string;
    /**
     * Display Name
     */
    display_name?: string | null;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
    active_car?: CarSummary | null;
};

/**
 * UsernameAvailability
 */
export type UsernameAvailability = {
    /**
     * Username
     */
    username: string;
    /**
     * Available
     */
    available: boolean;
    /**
     * Reason
     */
    reason?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * VisibilityMode
 */
export const VisibilityMode = {
    ON: 'on',
    FRIENDS_ONLY: 'friends_only',
    GHOST: 'ghost'
} as const;

/**
 * VisibilityMode
 */
export type VisibilityMode = typeof VisibilityMode[keyof typeof VisibilityMode];

/**
 * Waypoint
 *
 * A single waypoint along a route.
 */
export type Waypoint = {
    /**
     * Lat
     */
    lat: number;
    /**
     * Lng
     */
    lng: number;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Order
     */
    order?: number | null;
};

export type RegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type RegisterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
    /**
     * Successful Response
     */
    201: TokenResponse;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type AuthWithAppleData = {
    body: AppleAuthRequest;
    path?: never;
    query?: never;
    url: '/auth/apple';
};

export type AuthWithAppleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthWithAppleError = AuthWithAppleErrors[keyof AuthWithAppleErrors];

export type AuthWithAppleResponses = {
    /**
     * Successful Response
     */
    200: AppleAuthResponse;
};

export type AuthWithAppleResponse = AuthWithAppleResponses[keyof AuthWithAppleResponses];

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type RefreshData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type RefreshErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RefreshError = RefreshErrors[keyof RefreshErrors];

export type RefreshResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type RefreshResponse = RefreshResponses[keyof RefreshResponses];

export type LogoutData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type CheckUsernameData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Username
         */
        username: string;
    };
    url: '/users/check-username';
};

export type CheckUsernameErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CheckUsernameError = CheckUsernameErrors[keyof CheckUsernameErrors];

export type CheckUsernameResponses = {
    /**
     * Successful Response
     */
    200: UsernameAvailability;
};

export type CheckUsernameResponse = CheckUsernameResponses[keyof CheckUsernameResponses];

export type DeleteAccountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type DeleteAccountResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type DeleteAccountResponse = DeleteAccountResponses[keyof DeleteAccountResponses];

export type GetMyProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type GetMyProfileResponses = {
    /**
     * Successful Response
     */
    200: UserProfile;
};

export type GetMyProfileResponse = GetMyProfileResponses[keyof GetMyProfileResponses];

export type UpdateMyProfileData = {
    body: UpdateProfileRequest;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type UpdateMyProfileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateMyProfileError = UpdateMyProfileErrors[keyof UpdateMyProfileErrors];

export type UpdateMyProfileResponses = {
    /**
     * Successful Response
     */
    200: UserProfile;
};

export type UpdateMyProfileResponse = UpdateMyProfileResponses[keyof UpdateMyProfileResponses];

export type SearchUsersData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Q
         */
        q: string;
    };
    url: '/users/search';
};

export type SearchUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchUsersError = SearchUsersErrors[keyof SearchUsersErrors];

export type SearchUsersResponses = {
    /**
     * Response Users-Search Users
     *
     * Successful Response
     */
    200: Array<UserSearchResult>;
};

export type SearchUsersResponse = SearchUsersResponses[keyof SearchUsersResponses];

export type GetUserProfileData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/users/{user_id}';
};

export type GetUserProfileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserProfileError = GetUserProfileErrors[keyof GetUserProfileErrors];

export type GetUserProfileResponses = {
    /**
     * Successful Response
     */
    200: PublicUserProfile;
};

export type GetUserProfileResponse = GetUserProfileResponses[keyof GetUserProfileResponses];

export type ListCarsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/cars';
};

export type ListCarsResponses = {
    /**
     * Response Cars-List Cars
     *
     * Successful Response
     */
    200: Array<CarResponse>;
};

export type ListCarsResponse = ListCarsResponses[keyof ListCarsResponses];

export type CreateCarData = {
    body: CreateCarRequest;
    path?: never;
    query?: never;
    url: '/cars';
};

export type CreateCarErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCarError = CreateCarErrors[keyof CreateCarErrors];

export type CreateCarResponses = {
    /**
     * Successful Response
     */
    201: CarResponse;
};

export type CreateCarResponse = CreateCarResponses[keyof CreateCarResponses];

export type DeleteCarData = {
    body?: never;
    path: {
        /**
         * Car Id
         */
        car_id: string;
    };
    query?: never;
    url: '/cars/{car_id}';
};

export type DeleteCarErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteCarError = DeleteCarErrors[keyof DeleteCarErrors];

export type DeleteCarResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type DeleteCarResponse = DeleteCarResponses[keyof DeleteCarResponses];

export type UpdateCarData = {
    body: UpdateCarRequest;
    path: {
        /**
         * Car Id
         */
        car_id: string;
    };
    query?: never;
    url: '/cars/{car_id}';
};

export type UpdateCarErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCarError = UpdateCarErrors[keyof UpdateCarErrors];

export type UpdateCarResponses = {
    /**
     * Successful Response
     */
    200: CarResponse;
};

export type UpdateCarResponse = UpdateCarResponses[keyof UpdateCarResponses];

export type ActivateCarData = {
    body?: never;
    path: {
        /**
         * Car Id
         */
        car_id: string;
    };
    query?: never;
    url: '/cars/{car_id}/activate';
};

export type ActivateCarErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ActivateCarError = ActivateCarErrors[keyof ActivateCarErrors];

export type ActivateCarResponses = {
    /**
     * Successful Response
     */
    200: CarResponse;
};

export type ActivateCarResponse = ActivateCarResponses[keyof ActivateCarResponses];

export type ListFriendsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/friends';
};

export type ListFriendsResponses = {
    /**
     * Response Friends-List Friends
     *
     * Successful Response
     */
    200: Array<FriendProfile>;
};

export type ListFriendsResponse = ListFriendsResponses[keyof ListFriendsResponses];

export type ListFriendRequestsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/friends/requests';
};

export type ListFriendRequestsResponses = {
    /**
     * Response Friends-List Friend Requests
     *
     * Successful Response
     */
    200: Array<FriendRequestOut>;
};

export type ListFriendRequestsResponse = ListFriendRequestsResponses[keyof ListFriendRequestsResponses];

export type SendFriendRequestData = {
    body: FriendRequestCreate;
    path?: never;
    query?: never;
    url: '/friends/request';
};

export type SendFriendRequestErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SendFriendRequestError = SendFriendRequestErrors[keyof SendFriendRequestErrors];

export type SendFriendRequestResponses = {
    /**
     * Successful Response
     */
    201: MessageResponse;
};

export type SendFriendRequestResponse = SendFriendRequestResponses[keyof SendFriendRequestResponses];

export type AcceptFriendRequestData = {
    body: FriendRequestAction;
    path?: never;
    query?: never;
    url: '/friends/accept';
};

export type AcceptFriendRequestErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AcceptFriendRequestError = AcceptFriendRequestErrors[keyof AcceptFriendRequestErrors];

export type AcceptFriendRequestResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type AcceptFriendRequestResponse = AcceptFriendRequestResponses[keyof AcceptFriendRequestResponses];

export type DeclineFriendRequestData = {
    body: FriendRequestAction;
    path?: never;
    query?: never;
    url: '/friends/decline';
};

export type DeclineFriendRequestErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeclineFriendRequestError = DeclineFriendRequestErrors[keyof DeclineFriendRequestErrors];

export type DeclineFriendRequestResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type DeclineFriendRequestResponse = DeclineFriendRequestResponses[keyof DeclineFriendRequestResponses];

export type RemoveFriendData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/friends/{user_id}';
};

export type RemoveFriendErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemoveFriendError = RemoveFriendErrors[keyof RemoveFriendErrors];

export type RemoveFriendResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type RemoveFriendResponse = RemoveFriendResponses[keyof RemoveFriendResponses];

export type CreateConvoyData = {
    body: CreateConvoyRequest;
    path?: never;
    query?: never;
    url: '/convoys';
};

export type CreateConvoyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateConvoyError = CreateConvoyErrors[keyof CreateConvoyErrors];

export type CreateConvoyResponses = {
    /**
     * Successful Response
     */
    201: ConvoyResponse;
};

export type CreateConvoyResponse = CreateConvoyResponses[keyof CreateConvoyResponses];

export type GetConvoyData = {
    body?: never;
    path: {
        /**
         * Convoy Id
         */
        convoy_id: string;
    };
    query?: never;
    url: '/convoys/{convoy_id}';
};

export type GetConvoyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetConvoyError = GetConvoyErrors[keyof GetConvoyErrors];

export type GetConvoyResponses = {
    /**
     * Successful Response
     */
    200: ConvoyResponse;
};

export type GetConvoyResponse = GetConvoyResponses[keyof GetConvoyResponses];

export type UpdateConvoyData = {
    body: UpdateConvoyRequest;
    path: {
        /**
         * Convoy Id
         */
        convoy_id: string;
    };
    query?: never;
    url: '/convoys/{convoy_id}';
};

export type UpdateConvoyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateConvoyError = UpdateConvoyErrors[keyof UpdateConvoyErrors];

export type UpdateConvoyResponses = {
    /**
     * Successful Response
     */
    200: ConvoyResponse;
};

export type UpdateConvoyResponse = UpdateConvoyResponses[keyof UpdateConvoyResponses];

export type EndConvoyData = {
    body?: never;
    path: {
        /**
         * Convoy Id
         */
        convoy_id: string;
    };
    query?: never;
    url: '/convoys/{convoy_id}/end';
};

export type EndConvoyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EndConvoyError = EndConvoyErrors[keyof EndConvoyErrors];

export type EndConvoyResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type EndConvoyResponse = EndConvoyResponses[keyof EndConvoyResponses];

export type JoinConvoyData = {
    body?: never;
    path: {
        /**
         * Convoy Id
         */
        convoy_id: string;
    };
    query?: never;
    url: '/convoys/{convoy_id}/join';
};

export type JoinConvoyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type JoinConvoyError = JoinConvoyErrors[keyof JoinConvoyErrors];

export type JoinConvoyResponses = {
    /**
     * Successful Response
     */
    200: ConvoyResponse;
};

export type JoinConvoyResponse = JoinConvoyResponses[keyof JoinConvoyResponses];

export type RequestToJoinData = {
    body?: never;
    path: {
        /**
         * Convoy Id
         */
        convoy_id: string;
    };
    query?: never;
    url: '/convoys/{convoy_id}/request';
};

export type RequestToJoinErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RequestToJoinError = RequestToJoinErrors[keyof RequestToJoinErrors];

export type RequestToJoinResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type RequestToJoinResponse = RequestToJoinResponses[keyof RequestToJoinResponses];

export type AcceptJoinRequestData = {
    body?: never;
    path: {
        /**
         * Convoy Id
         */
        convoy_id: string;
        /**
         * Request Id
         */
        request_id: string;
    };
    query?: never;
    url: '/convoys/{convoy_id}/request/{request_id}/accept';
};

export type AcceptJoinRequestErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AcceptJoinRequestError = AcceptJoinRequestErrors[keyof AcceptJoinRequestErrors];

export type AcceptJoinRequestResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type AcceptJoinRequestResponse = AcceptJoinRequestResponses[keyof AcceptJoinRequestResponses];

export type DeclineJoinRequestData = {
    body?: never;
    path: {
        /**
         * Convoy Id
         */
        convoy_id: string;
        /**
         * Request Id
         */
        request_id: string;
    };
    query?: never;
    url: '/convoys/{convoy_id}/request/{request_id}/decline';
};

export type DeclineJoinRequestErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeclineJoinRequestError = DeclineJoinRequestErrors[keyof DeclineJoinRequestErrors];

export type DeclineJoinRequestResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type DeclineJoinRequestResponse = DeclineJoinRequestResponses[keyof DeclineJoinRequestResponses];

export type LeaveConvoyData = {
    body?: never;
    path: {
        /**
         * Convoy Id
         */
        convoy_id: string;
    };
    query?: never;
    url: '/convoys/{convoy_id}/leave';
};

export type LeaveConvoyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LeaveConvoyError = LeaveConvoyErrors[keyof LeaveConvoyErrors];

export type LeaveConvoyResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type LeaveConvoyResponse = LeaveConvoyResponses[keyof LeaveConvoyResponses];

export type InviteToConvoyData = {
    body: InviteRequest;
    path: {
        /**
         * Convoy Id
         */
        convoy_id: string;
    };
    query?: never;
    url: '/convoys/{convoy_id}/invite';
};

export type InviteToConvoyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type InviteToConvoyError = InviteToConvoyErrors[keyof InviteToConvoyErrors];

export type InviteToConvoyResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type InviteToConvoyResponse = InviteToConvoyResponses[keyof InviteToConvoyResponses];

export type KickMemberData = {
    body: KickRequest;
    path: {
        /**
         * Convoy Id
         */
        convoy_id: string;
    };
    query?: never;
    url: '/convoys/{convoy_id}/kick';
};

export type KickMemberErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type KickMemberError = KickMemberErrors[keyof KickMemberErrors];

export type KickMemberResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type KickMemberResponse = KickMemberResponses[keyof KickMemberResponses];

export type GetMessagesData = {
    body?: never;
    path: {
        /**
         * Convoy Id
         */
        convoy_id: string;
    };
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Before
         *
         * ISO 8601 timestamp for cursor-based pagination
         */
        before?: string | null;
    };
    url: '/convoys/{convoy_id}/messages';
};

export type GetMessagesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMessagesError = GetMessagesErrors[keyof GetMessagesErrors];

export type GetMessagesResponses = {
    /**
     * Response Convoys-Get Messages
     *
     * Successful Response
     */
    200: Array<ConvoyMessageOut>;
};

export type GetMessagesResponse = GetMessagesResponses[keyof GetMessagesResponses];

export type SendMessageData = {
    body: SendMessageRequest;
    path: {
        /**
         * Convoy Id
         */
        convoy_id: string;
    };
    query?: never;
    url: '/convoys/{convoy_id}/messages';
};

export type SendMessageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SendMessageError = SendMessageErrors[keyof SendMessageErrors];

export type SendMessageResponses = {
    /**
     * Successful Response
     */
    201: ConvoyMessageOut;
};

export type SendMessageResponse = SendMessageResponses[keyof SendMessageResponses];

export type SendQuickActionData = {
    body: QuickActionRequest;
    path: {
        /**
         * Convoy Id
         */
        convoy_id: string;
    };
    query?: never;
    url: '/convoys/{convoy_id}/quick-action';
};

export type SendQuickActionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SendQuickActionError = SendQuickActionErrors[keyof SendQuickActionErrors];

export type SendQuickActionResponses = {
    /**
     * Successful Response
     */
    201: ConvoyMessageOut;
};

export type SendQuickActionResponse = SendQuickActionResponses[keyof SendQuickActionResponses];

export type GetActiveRouteData = {
    body?: never;
    path: {
        /**
         * Convoy Id
         */
        convoy_id: string;
    };
    query?: never;
    url: '/convoys/{convoy_id}/route';
};

export type GetActiveRouteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetActiveRouteError = GetActiveRouteErrors[keyof GetActiveRouteErrors];

export type GetActiveRouteResponses = {
    /**
     * Response Convoys-Get Active Route
     *
     * Successful Response
     */
    200: RouteResponse | null;
};

export type GetActiveRouteResponse = GetActiveRouteResponses[keyof GetActiveRouteResponses];

export type SetRouteData = {
    body: SetRouteRequest;
    path: {
        /**
         * Convoy Id
         */
        convoy_id: string;
    };
    query?: never;
    url: '/convoys/{convoy_id}/route';
};

export type SetRouteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetRouteError = SetRouteErrors[keyof SetRouteErrors];

export type SetRouteResponses = {
    /**
     * Successful Response
     */
    201: RouteResponse;
};

export type SetRouteResponse = SetRouteResponses[keyof SetRouteResponses];

export type GetSpatialConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/spatial/config';
};

export type GetSpatialConfigResponses = {
    /**
     * Response Spatial-Get Spatial Config
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetSpatialConfigResponse = GetSpatialConfigResponses[keyof GetSpatialConfigResponses];

export type DebugSpatialStoreData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/spatial/debug';
};

export type DebugSpatialStoreResponses = {
    /**
     * Response Spatial-Debug Spatial Store
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type DebugSpatialStoreResponse = DebugSpatialStoreResponses[keyof DebugSpatialStoreResponses];

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckResponses = {
    /**
     * Response System-Health Check
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type HealthCheckResponse = HealthCheckResponses[keyof HealthCheckResponses];
