"""initial_schema

Revision ID: 73dedd7af426
Revises: 
Create Date: 2026-06-09 21:47:25.839246+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73dedd7af426'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('apple_id', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('visibility', sa.Enum('on', 'friends_only', 'ghost', name='visibility_mode'), server_default='on', nullable=False),
    sa.Column('discovery_radius_miles', sa.Integer(), server_default='15', nullable=False),
    sa.Column('speed_unit', sa.Enum('mph', 'kph', name='speed_unit'), server_default='mph', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_apple_id'), 'users', ['apple_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('cars',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('trim', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('mods', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cars_one_active_per_user', 'cars', ['user_id'], unique=True, postgresql_where=sa.text('is_active IS true'))
    op.create_index(op.f('ix_cars_user_id'), 'cars', ['user_id'], unique=False)
    op.create_table('convoys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('leader_id', sa.UUID(), nullable=False),
    sa.Column('visibility', sa.Enum('public', 'private', name='convoy_visibility'), nullable=False),
    sa.Column('status', sa.Enum('forming', 'active', 'ended', name='convoy_status'), nullable=False),
    sa.Column('destination_name', sa.Text(), nullable=True),
    sa.Column('destination_point', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['leader_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_convoys_destination_point', 'convoys', ['destination_point'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_convoys_leader_id'), 'convoys', ['leader_id'], unique=False)
    op.create_table('friendships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('addressee_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', name='friendship_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['addressee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_friendships_addressee_id'), 'friendships', ['addressee_id'], unique=False)
    op.create_index(op.f('ix_friendships_requester_id'), 'friendships', ['requester_id'], unique=False)
    op.create_index('ix_friendships_unique_pair', 'friendships', ['requester_id', 'addressee_id'], unique=True)
    op.create_table('push_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_token', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_token')
    )
    op.create_index(op.f('ix_push_tokens_user_id'), 'push_tokens', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('convoy_join_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('convoy_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', name='join_request_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['convoy_id'], ['convoys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_convoy_join_requests_convoy_id'), 'convoy_join_requests', ['convoy_id'], unique=False)
    op.create_index(op.f('ix_convoy_join_requests_user_id'), 'convoy_join_requests', ['user_id'], unique=False)
    op.create_table('convoy_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('convoy_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('leader', 'member', name='convoy_member_role'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['convoy_id'], ['convoys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_convoy_members_convoy_id'), 'convoy_members', ['convoy_id'], unique=False)
    op.create_index('ix_convoy_members_unique', 'convoy_members', ['convoy_id', 'user_id'], unique=True)
    op.create_index(op.f('ix_convoy_members_user_id'), 'convoy_members', ['user_id'], unique=False)
    op.create_table('convoy_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('convoy_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.Enum('text', 'system', 'quick_action', name='message_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['convoy_id'], ['convoys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_convoy_messages_convoy_created', 'convoy_messages', ['convoy_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_convoy_messages_convoy_id'), 'convoy_messages', ['convoy_id'], unique=False)
    op.create_index(op.f('ix_convoy_messages_created_at'), 'convoy_messages', ['created_at'], unique=False)
    op.create_table('convoy_routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('convoy_id', sa.UUID(), nullable=False),
    sa.Column('set_by_user_id', sa.UUID(), nullable=False),
    sa.Column('destination_name', sa.Text(), nullable=False),
    sa.Column('destination_point', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('waypoints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('route_geometry', geoalchemy2.types.Geography(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['convoy_id'], ['convoys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['set_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_convoy_routes_destination_point', 'convoy_routes', ['destination_point'], unique=False, postgresql_using='gist')
    op.create_index('idx_convoy_routes_route_geometry', 'convoy_routes', ['route_geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_convoy_routes_convoy_id'), 'convoy_routes', ['convoy_id'], unique=False)
    op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_index(op.f('ix_convoy_routes_convoy_id'), table_name='convoy_routes')
    op.drop_index('idx_convoy_routes_route_geometry', table_name='convoy_routes', postgresql_using='gist')
    op.drop_index('idx_convoy_routes_destination_point', table_name='convoy_routes', postgresql_using='gist')
    op.drop_table('convoy_routes')
    op.drop_index(op.f('ix_convoy_messages_created_at'), table_name='convoy_messages')
    op.drop_index(op.f('ix_convoy_messages_convoy_id'), table_name='convoy_messages')
    op.drop_index('ix_convoy_messages_convoy_created', table_name='convoy_messages')
    op.drop_table('convoy_messages')
    op.drop_index(op.f('ix_convoy_members_user_id'), table_name='convoy_members')
    op.drop_index('ix_convoy_members_unique', table_name='convoy_members')
    op.drop_index(op.f('ix_convoy_members_convoy_id'), table_name='convoy_members')
    op.drop_table('convoy_members')
    op.drop_index(op.f('ix_convoy_join_requests_user_id'), table_name='convoy_join_requests')
    op.drop_index(op.f('ix_convoy_join_requests_convoy_id'), table_name='convoy_join_requests')
    op.drop_table('convoy_join_requests')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_push_tokens_user_id'), table_name='push_tokens')
    op.drop_table('push_tokens')
    op.drop_index('ix_friendships_unique_pair', table_name='friendships')
    op.drop_index(op.f('ix_friendships_requester_id'), table_name='friendships')
    op.drop_index(op.f('ix_friendships_addressee_id'), table_name='friendships')
    op.drop_table('friendships')
    op.drop_index(op.f('ix_convoys_leader_id'), table_name='convoys')
    op.drop_index('idx_convoys_destination_point', table_name='convoys', postgresql_using='gist')
    op.drop_table('convoys')
    op.drop_index(op.f('ix_cars_user_id'), table_name='cars')
    op.drop_index('ix_cars_one_active_per_user', table_name='cars', postgresql_where=sa.text('is_active IS true'))
    op.drop_table('cars')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_apple_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
